[workspace]
resolver = "2"

members =  [
	"axdevice_base",
]

[workspace.package]
version = "0.1.0"
authors = ["Hui Xiao <1127751018@qq.com>"]
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = ""
repository = ""

[workspace.dependencies]
axdevice_base = { path = "axdevice_base", version = "0.1"}